### PR TITLE
Added ability to have non-spanning instances on multiple screens in Gnome and KDE

### PR DESCRIPTION
**Pull request by rsucco**
I noticed that in gnome, multimonitor setups are a bit finnicky. They work when you set spanning=True, but the top menu bar in gnome messes up the alignment and it ends up with the classification bar on the secondary screen being lower than it should be, potentially blocking UI elements. So, I implemented functionality for spanning=false on multiple displays. I also added a value called taskbar_offset, which corrects for the fact that Gnome doesn't allow you to draw over or under the taskbar, but it also doesn't report the size of the taskbar when you're getting the size of the screen, meaning that the lower bar from the primary display will partially stick out by 80 pixels or so onto the secondary display, which is a bit unsightly. I found 70 to be a good default taskbar_offset value, but your mileage may vary. I also slightly modified the autostart .dekstop file in the readme to include KDE, and have tested it with both gnome and KDE on Ubuntu/Kubuntu and it's working great on those two. I haven't tested it in XFCE or any other distro.

This is a fundamentally hacky solution to the problem, and it could be completely fixed by re-writing into python 3 and using the gtk3 method get_monitor_workarea instead of get_monitor_geometry, but I couldn't find any simple way to replicate this functionality in Python 2, and didn't have time to refactor the whole thing. Hopefully this is still useful to somebody. Thanks for all the work on getting this project up and running in the first place, even with having to modify it a little bit myself it still saved me a ton of time versus writing the whole thing from scratch.

### CODE REVIEW

**Comment by rsucco** [comment]
I’ve also had requests from people in my organization to implement functionality to be able to, if not temporarily close the banner (I have esc=false for policy reasons), at least be able to toggle it between top and bottom dynamically in case it’s covering up an essential UI element that they can’t click on. This seems like it would be fairly easy to implement and I’ll probably have it up and running here sometime next week, so if this PR gets accepted I’ll probably send that one your way too soon.

**Comment by fcaviggia** [comment]
Red Hat has taken over the project - they will have to re-factor this code for Python 3 and GTK updates.  I wish I had more time to maintain this, but my free time is gone with a family and the demands of my job.

**Comment by fcaviggia** [comment]
Code looks good and I'm good with the default functionality.

**Comment by rsucco** [comment]
No worries, thanks for the info. I should be able to port the non-hackjob solution to their fork fairly easily then. Thanks for the heads-up and for creating this in the first place. This and your hardened-kickstart projects have saved me many hours of work.

**Comment by fcaviggia** [comment]
Glad to hear that my work has saved time - I've been working on some major policy stuff these days. I miss coding - I only get to look at what other people do for the most part these days...

**Comment by kenyon** [comment]
> Red Hat has taken over the project - they will have to re-factor this code for Python 3 and GTK updates. I wish I had more time to maintain this, but my free time is gone with a family and the demands of my job.

@fcaviggia where is the Red Hat project? Is it this one?: https://github.com/SecurityCentral/classification-banner/

**Comment by fcaviggia** [comment]
Yes. that's it.

**Pull request merged**
